/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorCard: typeof import('./src/components/ActorCard.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CastMemberCard: typeof import('./src/components/CastMemberCard.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MovieCard: typeof import('./src/components/MovieCard.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProductionCard: typeof import('./src/components/ProductionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SystemHeader: typeof import('./src/components/SystemHeader.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
