/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorCard: typeof import('./src/components/ActorCard.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CastMemberCard: typeof import('./src/components/CastMemberCard.vue')['default']
    MovieCard: typeof import('./src/components/MovieCard.vue')['default']
    ProductionCard: typeof import('./src/components/ProductionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
  }
}
